import {
  port1,
  port3,
  port2,
  port4,
  port5,
  port6,
  port7,
  port8,
  port9,
  kripa,
  shivart,
  tyor,
  grfinance,
  codeseeker,
  starson,
  finance3,
  finance2,
  drpaterson,
  takecare,
  educator,
  LearnPress,
  healthyheart,
  doctroAppointmnet,
  hotel3,
  hotel4,
} from "../../Assets/Index";

export const cardImages = [
  {
    image: port1,
    text: `JHEV Motors`,
    to: "https://jhevmotors.com/",
    category: ["b2b", "b2c"],
  },
  {
    image: port2,
    text: `AFS Deals`,
    to: "https://www.afsdeal.com/",
    category: ["e-commerce", "b2c"],
  },
  {
    image: port3,
    text: `Esquareeduwing Pvt. Ltd.`,
    to: "https://esquareeduwings.com/",
    category: ["education"],
  },
  {
    image: port4,
    text: `Aggarwal Caterer `,
    to: "https://aggarwalcaterers.in/",
    category: ["b2c"],
  },
  {
    image: port5,
    text: `shivshakti aluminium`,
    to: "https://shivshaktialuminiums.com/",
    category: ["b2b", "b2c"],
  },
  {
    image: port6,
    text: `ksec`,
    to: "https://ksec.deepmart.shop/",
    category: ["industries", "b2b"],
  },
  {
    image: port7,
    text: `star motors`,
    to: "https://starmotor.deepmart.shop/",
    category: ["b2c"],
  },
  { image: port8, text: `Mic N melon`, to: "https://micnmelons.deepmart.shop/", category: ["b2b", "b2c"] },
  {
    image: port9,
    text: `tuindestries`,
    to: "https://tuindustries.in/",
    category: ["b2b", "industries"],
  },
  {
    image: kripa,
    text: `Kripa Creations`,
    to: "https://kripakreation.com/",
    category: ["b2c", "e-commerce"],
  },
  {
    image: shivart,
    text: `Shiv Art`,
    to: "https://shivaarts.com/",
    category: ["b2b", "industries"],
  },
  {
    image: tyor,
    text: `tyoharwala`,
    to: "https://tyoharwala.com/",
    category: ["b2c", "e-commerce", "b2b"],
  },
  {
    image: grfinance,
    text: `GR-Finance`,
    to: "https://grfinancial.in/auth/login",
    category: ["finance"],
  },
  {
    image: codeseeker,
    text: `Code Seeker`,
    to: "https://codeseekeracademy.com/",
    category: ["education", "b2b"],
  },
  {
    image: starson,
    text: `Star Son`,
    to: "https://starsonscientific.com/",
    category: ["b2b"],
  },
  {
    image: doctroAppointmnet,
    text: `doctris`,
    to: "https://shreethemes.in/doctris/layouts/landing/index-two.html",
    category: ["hospital"],
  },
  {
    image: healthyheart,
    text: `medicare`,
    to: "https://medicare.bold-themes.com/cardiology/",
    category: ["hospital"],
  },
  {
    image: LearnPress,
    text: `eduma`,
    to: "https://eduma.thimpress.com/demo-classic/",
    category: ["education"],
  },
  {
    image: educator,
    text: `educator`,
    to: "https://educator.qodeinteractive.com/language-school/",
    category: ["education"],
  },
  {
    image: hotel3,
    text: `Hotel booking`,
    to: "https://demo.himaratheme.com/",
    category: ["hotel"],
  },
  {
    image: hotel4,
    text: `Hotel booking`,
    to: "http://www.nicdarkthemes.com/themes/hotel-booking/wp/demo/hotel/ ",
    category: ["hotel"],
  },
  {
    image: takecare,
    text: `cliniq`,
    to: "https://cliniq.bold-themes.com/futuristic/home/home-03/  ",
    category: ["hospital"],
  },
  {
    image: drpaterson,
    text: `dr. patterson`,
    to: "https://patterson.themerex.net/",
    category: ["hospital"],
  },
  {
    image: finance2,
    text: `finance`,
    to: "https://finance.bold-themes.com/main-demo/landing-page/financial-software/ ",
    category: ["finance"],
  },
  {
    image: finance3,
    text: `finance`,
    to: "https://finance.bold-themes.com/main-demo/landing-page/consulting-company/",
    category: ["finance"],
  },
];
